import type { Agent, Portfolio } from './types';

export const S_P500_TICKERS: string[] = [
  'NVDA',
  'AAPL',
  'MSFT',
  'AMZN',
  'GOOGL',
  'AVGO',
  'GOOG',
  'META',
  'TSLA',
  'BRK-B',
  'LLY',
  'JPM',
  'WMT',
  'V',
  'ORCL',
  'MA',
  'XOM',
  'NFLX',
  'JNJ',
  'PLTR',
  'AMD',
  'ABBV',
  'COST',
  'BAC',
  'HD',
  'PG',
  'GE',
  'KO',
  'UNH',
  'CVX',
  'IBM',
  'CSCO',
  'MU',
  'WFC',
  'MS',
  'CAT',
  'AXP',
  'GS',
  'PM',
  'TMUS',
  'RTX',
  'CRM',
  'MRK',
  'ABT',
  'TMO',
  'MCD',
  'DIS',
  'ISRG',
  'LRCX',
  'LIN',
  'APP',
  'PEP',
  'UBER',
  'QCOM',
  'C',
  'AMAT',
  'INTU',
  'T',
  'AMGN',
  'INTC',
  'NOW',
  'NEE',
  'SCHW',
  'APH',
  'VZ',
  'ANET',
  'BLK',
  'BKNG',
  'TJX',
  'KLAC',
  'GEV',
  'BSX',
  'DHR',
  'GILD',
  'ACN',
  'SPGI',
  'BA',
  'TXN',
  'PFE',
  'PANW',
  'ETN',
  'COF',
  'ADBE',
  'SYK',
  'CRWD',
  'UNP',
  'LOW',
  'WELL',
  'PGR',
  'DE',
  'HON',
  'MDT',
  'HOOD',
  'ADI',
  'PLD',
  'CB',
  'BX',
  'CEG',
  'COP',
  'VRTX',
  'KKR',
  'HCA',
  'PH',
  'LMT',
  'MCK',
  'CVS',
  'ADP',
  'NEM',
  'CMCSA',
  'CME',
  'SO',
  'SBUX',
  'BMY',
  'MO',
  'DUK',
  'NKE',
  'DELL',
  'GD',
  'TT',
  'MMM',
  'MMC',
  'MCO',
  'ICE',
  'CDNS',
  'AMT',
  'SHW',
  'DASH',
  'HWM',
  'ORLY',
  'WM',
  'COIN',
  'UPS',
  'JCI',
  'NOC',
  'EQIX',
  'BK',
  'MAR',
  'APO',
  'GLW',
  'AON',
  'EMR',
  'SNPS',
  'CTAS',
  'ECL',
  'USB',
  'MDLZ',
  'WMB',
  'ABNB',
  'CI',
  'ELV',
  'TDG',
  'PNC',
  'TEL',
  'REGN',
  'RCL',
  'ITW',
  'COR',
  'MNST',
  'PWR',
  'GM',
  'DDOG',
  'CMI',
  'CSX',
  'AEP',
  'AJG',
  'MSI',
  'NSC',
  'ADSK',
  'HLT',
  'TRV',
  'FDX',
  'CL',
  'RSG',
  'AZO',
  'PYPL',
  'FTNT',
  'VST',
  'WDAY',
  'SRE',
  'FCX',
  'SPG',
  'KMI',
  'AFL',
  'STX',
  'MPC',
  'EOG',
  'APD',
  'TFC',
  'IDXX',
  'WDC',
  'DLR',
  'LHX',
  'PSX',
  'WBD',
  'URI',
  'BDX',
  'VLO',
  'ALL',
  'SLB',
  'ZTS',
  'F',
  'ROST',
  'MET',
  'O',
  'D',
  'PCAR',
  'NXPI',
  'NDAQ',
  'EA',
  'EW',
  'ROP',
  'CAH',
  'PSA',
  'XEL',
  'BKR',
  'FAST',
  'CARR',
  'CBRE',
  'EXC',
  'MPWR',
  'AME',
  'LVS',
  'CTVA',
  'GWW',
  'AXON',
  'TTWO',
  'ROK',
  'MSCI',
  'AMP',
  'KR',
  'OKE',
  'ETR',
  'DHI',
  'A',
  'FICO',
  'AIG',
  'FANG',
  'TGT',
  'PEG',
  'YUM',
  'OXY',
  'CMG',
  'CCI',
  'CPRT',
  'PAYX',
  'EBAY',
  'XYZ',
  'DAL',
  'VMC',
  'GRMN',
  'EQT',
  'PRU',
  'IQV',
  'MLM',
  'HIG',
  'PCG',
  'RMD',
  'XYL',
  'TRGP',
  'KDP',
  'WEC',
  'SYY',
  'HSY',
  'ED',
  'VTR',
  'WAB',
  'CCL',
  'CTSH',
  'OTIS',
  'KMB',
  'NUE',
  'FI',
  'FIS',
  'STT',
  'GEHC',
  'EXPE',
  'EL',
  'ACGL',
  'RJF',
  'LYV',
  'VICI',
  'KVUE',
  'NRG',
  'IBKR',
  'UAL',
  'LEN',
  'KEYS',
  'IR',
  'HPE',
  'WTW',
  'MCHP',
  'MTD',
  'VRSK',
  'TSCO',
  'IRM',
  'ODFL',
  'HUM',
  'KHC',
  'EME',
  'WRB',
  'DTE',
  'CSGP',
  'K',
  'MTB',
  'FSLR',
  'ATO',
  'AEE',
  'EXE',
  'FITB',
  'ROL',
  'EXR',
  'TER',
  'ADM',
  'ES',
  'BRO',
  'CBOE',
  'PPL',
  'CHTR',
  'SYF',
  'FE',
  'STE',
  'BR',
  'CINF',
  'CNP',
  'EFX',
  'AWK',
  'AVB',
  'DOV',
  'NTRS',
  'LDOS',
  'HBAN',
  'GIS',
  'TDY',
  'VLTO',
  'ULTA',
  'HUBB',
  'PODD',
  'BIIB',
  'HPQ',
  'PHM',
  'WSM',
  'VRSN',
  'STLD',
  'DXCM',
  'WAT',
  'TPL',
  'DG',
  'JBL',
  'EQR',
  'TROW',
  'HAL',
  'CMS',
  'STZ',
  'EIX',
  'SMCI',
  'CFG',
  'NTAP',
  'RF',
  'DVN',
  'LH',
  'PPG',
  'DLTR',
  'SBAC',
  'L',
  'PTC',
  'TPR',
  'INCY',
  'TTD',
  'DGX',
  'NI',
  'RL',
  'CHD',
  'IP',
  'LULU',
  'DRI',
  'CPAY',
  'TYL',
  'ON',
  'CTRA',
  'NVR',
  'WST',
  'TRMB',
  'Q',
  'KEY',
  'AMCR',
  'TSN',
  'CDW',
  'EXPD',
  'BG',
  'SW',
  'PFG',
  'J',
  'GPN',
  'PKG',
  'CHRW',
  'APTV',
  'CNC',
  'SNA',
  'GDDY',
  'INVH',
  'PNR',
  'GPC',
  'MKC',
  'EVRG',
  'ZBH',
  'LNT',
  'LUV',
  'DD',
  'PSKY',
  'IFF',
  'GEN',
  'LII',
  'IT',
  'HOLX',
  'ESS',
  'FTV',
  'BBY',
  'WY',
  'JBHT',
  'DOW',
  'MAA',
  'ERIE',
  'TXT',
  'COO',
  'ALLE',
  'UHS',
  'TKO',
  'OMC',
  'FOX',
  'KIM',
  'FOXA',
  'LYB',
  'FFIV',
  'DPZ',
  'EG',
  'AVY',
  'NDSN',
  'CF',
  'BF-B',
  'WYNN',
  'ZBRA',
  'MAS',
  'AKAM',
  'REG',
  'ALB',
  'CLX',
  'SOLV',
  'IEX',
  'VTRS',
  'HII',
  'BALL',
  'HST',
  'DECK',
  'DOC',
  'HRL',
  'JKHY',
  'BEN',
  'SJM',
  'BLDR',
  'UDR',
  'BXP',
  'AIZ',
  'HAS',
  'DAY',
  'CPT',
  'IVZ',
  'RVTY',
  'PNW',
  'GL',
  'SWK',
  'SWKS',
  'MRNA',
  'ALGN',
  'FDS',
  'AES',
  'EPAM',
  'NWSA',
  'BAX',
  'TECH',
  'GNRC',
  'ARE',
  'POOL',
  'CPB',
  'TAP',
  'IPG',
  'AOS',
  'PAYC',
  'MGM',
  'DVA',
  'NCLH',
  'APA',
  'HSIC',
  'FRT',
  'CRL',
  'CAG',
  'LW',
  'MOS',
  'LKQ',
  'MTCH',
  'MOH',
  'SOLS',
  'MHK',
  'NWS'
];

export const INITIAL_CASH = 10000;
export const RISK_FREE_RATE = 0.02; // Annual risk-free rate for Sharpe ratio
export const TRADING_DAYS_PER_YEAR = 252;
export const MAX_POSITION_SIZE_PERCENT = 0.10; // 10%
export const S_P500_BENCHMARK_ID = 'SPY';
export const AI_MANAGERS_INDEX_ID = 'AIMI';
export const AGENT_COLORS = ['#8884d8', '#ffc658', '#82ca9d', '#ff8042', '#00C49F', '#0088FE', '#FF6B9D', '#C44569', '#6C5CE7', '#A29BFE'];
export const BENCHMARK_COLORS = {
    [S_P500_BENCHMARK_ID]: '#A3A3A3',
    [AI_MANAGERS_INDEX_ID]: '#F5F5F5'
};

const initialPortfolio: Portfolio = {
  cash: INITIAL_CASH,
  positions: {},
};

// ============================================================================
// TRADER CONFIGURATION
// ============================================================================
// To add a new trader, simply add a new entry to TRADER_CONFIGS below.
// Each trader needs:
//   - id: unique identifier (used internally)
//   - name: display name (shown in UI)
//   - model: OpenRouter model identifier (e.g., 'google/gemini-2.0-flash-exp:free')
//   - systemPrompt: custom trading strategy/personality prompt (optional - will use UNIFIED_SYSTEM_PROMPT if not provided)
//   - color: hex color for charts (optional, will auto-assign if not provided)
//
// Popular OpenRouter models:
//   - 'google/gemini-2.0-flash-exp:free' (free tier, may have rate limits)
//   - 'google/gemini-pro-1.5'
//   - 'anthropic/claude-3.5-sonnet'
//   - 'anthropic/claude-3-opus'
//   - 'openai/gpt-4o'
//   - 'openai/gpt-4-turbo'
//   - 'x-ai/grok-2-1212' (Grok model - check OpenRouter for latest)
//   - 'deepseek/deepseek-chat'
//   - 'qwen/qwen-2.5-72b-instruct'
//   - 'meta-llama/llama-3.1-70b-instruct'
// Note: Some models may require API keys or have rate limits. Check OpenRouter docs.
// ============================================================================

// Unified system prompt for all agents to ensure fair comparison
export const UNIFIED_SYSTEM_PROMPT = `You are a portfolio manager operating in an equity-trading environment.
Your goal is to maximize risk-adjusted returns while adhering to trading rules.
Evaluate market signals, sector performance, and stock momentum based on the provided data.
Maintain diversification and avoid excessive turnover.
Focus on quality companies with strong fundamentals.

CRITICAL REQUIREMENT: You MUST make trading decisions every day. You cannot hold 100% cash.
- If you have cash, you MUST buy stocks that meet your criteria
- You must invest at least 50% of your portfolio in stocks
- Being too conservative and holding cash is NOT acceptable - you are a portfolio manager, not a cash holder
- Make at least one trade per day when you have cash available
- Your job is to invest, not to wait`;

interface TraderConfig {
  id: string;
  name: string;
  model: string; // OpenRouter model identifier
  systemPrompt?: string; // Optional - will use UNIFIED_SYSTEM_PROMPT if not provided
  color?: string;
}

export const TRADER_CONFIGS: TraderConfig[] = [
  {
    id: 'gemini-balanced',
    name: 'Gemini 2.5 Flash',
    model: 'google/gemini-2.5-flash',
    // systemPrompt not provided - will use UNIFIED_SYSTEM_PROMPT
  },
  {
    id: 'claude-prudent',
    name: 'Claude 3 haiku',
    model: 'anthropic/claude-3-haiku',
    // systemPrompt not provided - will use UNIFIED_SYSTEM_PROMPT
  },
  {
    id: 'grok-momentum',
    name: 'Grok 4 fast',
    model: 'x-ai/grok-4-fast',
    // systemPrompt not provided - will use UNIFIED_SYSTEM_PROMPT
  },
  {
    id: 'deepseek-analytical',
    name: 'DeepSeek Chat',
    model: 'deepseek/deepseek-chat',
    // systemPrompt not provided - will use UNIFIED_SYSTEM_PROMPT
  },
  {
    id: 'qwen-conservative',
    name: 'Qwen 2.5 72B',
    model: 'qwen/qwen-2.5-72b-instruct',
    // systemPrompt not provided - will use UNIFIED_SYSTEM_PROMPT
  },
];

// Helper function to create agents from trader configs
const createAgentsFromConfigs = (configs: TraderConfig[]): Agent[] => {
  return configs.map((config, index) => ({
    id: config.id,
    name: config.name,
    model: config.model,
    color: config.color || AGENT_COLORS[index % AGENT_COLORS.length],
    portfolio: { ...initialPortfolio, positions: {} },
    tradeHistory: [],
    performanceHistory: [],
    rationale: 'Awaiting first trading day.',
    rationaleHistory: { 0: 'Awaiting first trading day.' },
    systemPrompt: config.systemPrompt || UNIFIED_SYSTEM_PROMPT, // Use unified prompt if not provided
  } as Agent & { systemPrompt: string }));
};

export const INITIAL_AGENTS: Agent[] = createAgentsFromConfigs(TRADER_CONFIGS);